### ISSUE TITLE
Repackage and ship standalone

### ISSUE THREAD

**Issue by ghost** [pcfreak30/rocket-footer-js#2]
First off. I don't use this plug-in, so I cannot speak to it's value. But it's vision seems to be dead on with what slows down a majority of stock WordPress sites today. I see lots of possibility here. But it needs to be untangled from `rocket-footer` and rebranded before WordPress users, who are already wary of plug-ins slowing down or janking up their sites, to buy into it. Please tell me your thoughts.

**Comment by pcfreak30** [comment]
I have thought about it before, but it means integration with many different cache "systems" and I create things out of a need for myself or my work (as I assume many do). Since I am not interested in making a premium plugin shop, I doubt that I will be taking an initiative on this. To me wp-rocket works better than most systems and its a lot simpler overall so I have yet to invest time in many of the systems.
